# coding: utf-8

"""
    WSO2 API Manager - Publisher API

    This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_publisherclient
from wso2_apim_publisherclient.rest import ApiException
from wso2_apim_publisherclient.apis.throttling_tier_individual_api import ThrottlingTierIndividualApi


class TestThrottlingTierIndividualApi(unittest.TestCase):
    """ ThrottlingTierIndividualApi unit test stubs """

    def setUp(self):
        self.api = wso2_apim_publisherclient.apis.throttling_tier_individual_api.ThrottlingTierIndividualApi()

    def tearDown(self):
        pass

    def test_tiers_tier_level_tier_name_delete(self):
        """
        Test case for tiers_tier_level_tier_name_delete

        Delete a Tier
        """
        pass

    def test_tiers_tier_level_tier_name_get(self):
        """
        Test case for tiers_tier_level_tier_name_get

        Get details of a tier
        """
        pass

    def test_tiers_tier_level_tier_name_put(self):
        """
        Test case for tiers_tier_level_tier_name_put

        Update a Tier
        """
        pass

    def test_tiers_update_permission_post(self):
        """
        Test case for tiers_update_permission_post

        Update tier permission
        """
        pass


if __name__ == '__main__':
    unittest.main()
