# coding: utf-8

"""
    WSO2 API Manager - Publisher API

    This specifies a **RESTful API** for WSO2 **API Manager** - Publisher.  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification. 

    OpenAPI spec version: 0.11.0
    Contact: architecture@wso2.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import wso2_apim_publisherclient
from wso2_apim_publisherclient.rest import ApiException
from wso2_apim_publisherclient.apis.api_individual_api import APIIndividualApi


class TestAPIIndividualApi(unittest.TestCase):
    """ APIIndividualApi unit test stubs """

    def setUp(self):
        self.api = wso2_apim_publisherclient.apis.api_individual_api.APIIndividualApi()

    def tearDown(self):
        pass

    def test_apis_api_id_delete(self):
        """
        Test case for apis_api_id_delete

        Delete an API
        """
        pass

    def test_apis_api_id_get(self):
        """
        Test case for apis_api_id_get

        Get details of an API
        """
        pass

    def test_apis_api_id_policies_mediation_get(self):
        """
        Test case for apis_api_id_policies_mediation_get

        Retrieve/Search APIs 
        """
        pass

    def test_apis_api_id_policies_mediation_mediation_policy_id_delete(self):
        """
        Test case for apis_api_id_policies_mediation_mediation_policy_id_delete

        Delete an API
        """
        pass

    def test_apis_api_id_policies_mediation_mediation_policy_id_get(self):
        """
        Test case for apis_api_id_policies_mediation_mediation_policy_id_get

        Get a global mediation squence
        """
        pass

    def test_apis_api_id_policies_mediation_mediation_policy_id_put(self):
        """
        Test case for apis_api_id_policies_mediation_mediation_policy_id_put

        Update an mediation policy
        """
        pass

    def test_apis_api_id_policies_mediation_post(self):
        """
        Test case for apis_api_id_policies_mediation_post

        Upload a global mediation policy
        """
        pass

    def test_apis_api_id_put(self):
        """
        Test case for apis_api_id_put

        Update an API
        """
        pass

    def test_apis_api_id_swagger_get(self):
        """
        Test case for apis_api_id_swagger_get

        Get swagger definition
        """
        pass

    def test_apis_api_id_swagger_put(self):
        """
        Test case for apis_api_id_swagger_put

        Update swagger definition
        """
        pass

    def test_apis_api_id_thumbnail_get(self):
        """
        Test case for apis_api_id_thumbnail_get

        Get thumbnail image
        """
        pass

    def test_apis_api_id_thumbnail_post(self):
        """
        Test case for apis_api_id_thumbnail_post

        Upload a thumbnail image
        """
        pass

    def test_apis_change_lifecycle_post(self):
        """
        Test case for apis_change_lifecycle_post

        Change API Status
        """
        pass

    def test_apis_copy_api_post(self):
        """
        Test case for apis_copy_api_post

        Create a new API version
        """
        pass


if __name__ == '__main__':
    unittest.main()
